name: reels_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  blockies: ^0.1.2
  flutter:
    sdk: flutter
  path_provider: ^2.1.5
  permission_handler: ^12.0.0+1
  video_player: ^2.9.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/videos/
    - assets/video_metadata.json
